- name: Make sure that the apache is installed
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Make sure that the apache is running
  service:
    name: apache2
    state: started

- name: install packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - php-cgi
      - php-xsl
      - php-cgi
      - php-gd
      - php-mbstring
      - php-zip
      - php-xmlrpc
      - php-soap
      - php-intl
      - libapache2-mod-php
      - php-mysqlnd

- name: "apache  - Creating httpd.conf from template"
  template:
    src: "http.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  

- name: "apache2  - DocumentRoot Creation"
  file:
    path: "/var/www/html/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: restart-apache2
    
- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: restart-apache2

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify:
    - restart-apache2
- name: "mariadb - Package Installation"
  apt:
    name: 
      - mariadb-server
      - python3-mysqldb
    state: present
     

- name: "mariadb - Restarting/Enabling Service"
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: "mariadb - Setting RootPassword"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_password: ""
    user: "root"
    password: "{{ mariadb_root }}"
    host_all: true

- name: "mariadb - Removing Anonymous Users"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    user: ""
    state: absent
    host_all: true


- name: "mariadb - Removing test database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: "test"
    state: absent

- name: "mariadb - Creating Extra database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: "{{ mariadb_database }}"
    state: present

- name: "mariadb  - Creating Extra User"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: '{{ mariadb_database }}.*:ALL'

- name: "Wordpress - Downloading Archive File"
  get_url:
    url: https://wordpress.org/wordpress-5.8.tar.gz
    dest: /tmp/wordpress.tar.gz
 
- name: "Wordpress - Extracting Wordpress"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: true

- name: "Wordpress - Copying Contents To Docroot"
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/{{ http_host }}/
    remote_src: true
    owner: www-data
    group: www-data

- name: "Wordpress - Creating wp-config.php"
  template:
    src: wp-config.php.j2
    dest: "/var/www/html/{{ http_host }}/wp-config.php"
    owner: www-data
    group: www-data
  notify:
    - restart-apache2

